# Generated by Django 3.2 on 2021-04-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.TextField(default='movie'),
            preserve_default=False,
        ),
    ]
